#!/usr/bin/env bash
# This script transfers a file from client to server using scp

# Check if the number of argument is less than 3
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/

# Check if scp command was successful
if [ $? -eq 0 ]; then
	echo "File transfer completed successfully."
else
	echo "File transfer failed."
fi
