#!/usr/bin/env bash
#Bash script that displays "To infinity and Beyond indefinitely
#With a "sleep 2" in between each iteration
#Also displays "I am invincible!!!" when receiving a SIGTERM signal
while true
do
	echo "To infinity and beyond"
	sleep
	trap 'echo "I am invincible!!!"' SIGTERM
done
