#!/usr/bin/env bash
#This script displays numbers from 1 to 20
#Displays 4 and then "bad luck from china" for the 4th loop iteration
#Displays 9 and then "bad luck from japan" for the 9th loop iteration
#Displays 17 and then "bad luck frpm italy" for the 17th loop iteration

x=1

while [ $x -le 20 ]; do
	echo "$x"
	case $x in
	    4)
	        echo "bad luck from China"
		;;
	    9)
		echo "bad luck from Japan"
		;;
	    17)
		echo "bad luck from Italy"
		;;
	esac
	(( x++ ))
done
